-- 006: Seeds для публичного контента (lessons/news/events/banners/grammar_rules)
-- ⚠️  Файл регенерируется из живой БД. Не редактировать вручную:
--    bash scripts/regenerate-content-seeds.sh
-- Все вставки имеют ON CONFLICT (id) DO NOTHING — повторный прогон безопасен,
-- но НЕ обновляет существующие строки. Если нужно обновить prod — выполните
-- TRUNCATE + повторный seed на свежей БД, или применяйте UPDATE напрямую.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- lessons: добавляем mentor_track / required_level / rule_ids, если их ещё нет.
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS mentor_track VARCHAR(50);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS required_level VARCHAR(5);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS rule_ids JSONB DEFAULT '[]';

CREATE TABLE IF NOT EXISTS grammar_rules (
  id VARCHAR(64) PRIMARY KEY,
  topic VARCHAR(200) NOT NULL,
  title_kk VARCHAR(500) NOT NULL,
  title_ru VARCHAR(500) NOT NULL,
  level VARCHAR(5),
  description_kk TEXT,
  description_ru TEXT,
  examples JSONB DEFAULT '[]',
  exceptions JSONB DEFAULT '[]',
  rule_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_grammar_rules_order ON grammar_rules(rule_order);

-- ===========================================================================
-- DATA (regenerated from live DB)
-- ===========================================================================
--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13


--
-- Data for Name: banners; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO banners (id, title, image_url, link_url, is_active, sort_order, "position", subtitle_kk, subtitle_ru, created_at) VALUES ('00000000-0000-4000-8000-000000000901', 'Тіл-құралға қош келдіңіз', 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1600&q=80', '/ru/learn', true, 10, 'hero', 'Қазақ тілін AI-тәлімгермен үйреніңіз', 'Учите казахский язык с AI-учителем', '2026-04-21 21:37:31.071746+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO banners (id, title, image_url, link_url, is_active, sort_order, "position", subtitle_kk, subtitle_ru, created_at) VALUES ('00000000-0000-4000-8000-000000000902', 'Пройди тест уровня', 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1600&q=80', '/ru/test', true, 20, 'hero', 'Қазақ тілі деңгейіңізді 5 минутта анықтаңыз', 'Определите ваш уровень казахского за 5 минут', '2026-04-21 21:37:31.071746+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO banners (id, title, image_url, link_url, is_active, sort_order, "position", subtitle_kk, subtitle_ru, created_at) VALUES ('00000000-0000-4000-8000-000000000903', 'Новый курс KAZTEST', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=1600&q=80', '/ru/learn/kaztest', true, 30, 'hero', 'KAZTEST емтиханына толық дайындық — 5 секция', 'Полная подготовка к KAZTEST — 5 секций', '2026-04-21 21:37:31.071746+00') ON CONFLICT (id) DO NOTHING;


--
-- Data for Name: grammar_rules; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_03', 'Зат есім', 'Зат есімнің көптік жалғауы', 'Множественное число существительных', 'A1', 'Көптік жалғау -лар/-лер, -дар/-дер, -тар/-тер. Сөз соңындағы дыбысқа және буын үндестігіне байланысты таңдалады.', 'Окончания множественного числа: -лар/-лер, -дар/-дер, -тар/-тер. Выбор зависит от последнего звука и гармонии гласных.', '["бала-лар", "үй-лер", "ат-тар", "күн-дер", "жол-дар", "гүл-дер"]', '[]', 30, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_04', 'Зат есім', 'Септік жалғаулары', 'Падежные окончания', 'A2', 'Қазақ тілінде 7 септік бар: атау, ілік, барыс, табыс, жатыс, шығыс, көмектес.', 'В казахском языке 7 падежей: именительный, родительный, дательный, винительный, местный, исходный, творительный.', '["бала (атау)", "баланың (ілік)", "балаға (барыс)", "баланы (табыс)", "балада (жатыс)", "баладан (шығыс)", "баламен (көмектес)"]', '[]', 40, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_06', 'Сын есім', 'Сын есімнің шырайлары', 'Степени сравнения прилагательных', 'B1', 'Сын есімнің 4 шырайы бар: жай шырай (қосымшасыз: үлкен), салыстырмалы шырай (-рақ/-рек, -ырақ/-ірек, -лау/-леу: үлкенірек), күшейтпелі шырай (буын қайталау: қып-қызыл, көп-көк), асырмалы шырай (ең, тым, өте, аса: ең үлкен).', 'Четыре степени: положительная (без аффикса: үлкен), сравнительная (-рақ/-рек, -ырақ/-ірек, -лау/-леу: үлкенірек), эмфатическая / күшейтпелі (повтор слога: қып-қызыл, көп-көк), превосходная / асырмалы (ең, тым, өте, аса: ең үлкен).', '["үлкен → үлкенірек → ең үлкен", "жақсы → жақсырақ → ең жақсы", "қызыл → қып-қызыл (күшейтпелі)"]', '[]', 60, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_08', 'Етістік', 'Етістіктің шақтары: Өткен шақ', 'Времена глагола: Прошедшее время', 'A2', 'Жедел өткен шақ: -ды/-ді, -ты/-ті (жақын, көзбен көрілген әрекет). Бұрынғы өткен шақ: -ған/-ген, -қан/-кен (нәтижелі, перфектілі мән).', 'Недавнопрошедшее (очевидное): -ды/-ді, -ты/-ті — действие, свидетелем которого был говорящий. Перфектное (результативное): -ған/-ген, -қан/-кен — результат сохраняется к моменту речи.', '["Мен бардым (жедел/недавнопрошедшее)", "Мен барғанмын (перфектное)", "Ол келді", "Ол келген"]', '[]', 80, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_09', 'Етістік', 'Етістіктің шақтары: Келер шақ', 'Времена глагола: Будущее время', 'B1', 'Болжалды келер шақ: -ар/-ер дауыссыздан кейін, -р дауыстыдан кейін (мүмкіндік мағынасы). Мақсатты (намерение): -мақ/-мек, -бақ/-бек, -пақ/-пек.', 'Будущее предположительное: -ар/-ер после согласного, -р после гласного (значение «возможно сделает»). Будущее намерения: -мақ/-мек, -бақ/-бек, -пақ/-пек (значение «намерен сделать»).', '["Мен барармын", "Ол келер", "Мен оқымақпын", "Ол жаз-бақ"]', '[]', 90, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_10', 'Етістік', 'Етістіктің болымсыз түрі', 'Отрицательная форма глагола', 'A1', 'Болымсыздық -ма/-ме, -ба/-бе, -па/-пе жұрнақтарымен жасалады.', 'Отрицание образуется суффиксами -ма/-ме, -ба/-бе, -па/-пе.', '["бар-ма-ды", "кел-ме-ді", "жаз-ба-ды", "оқы-ма-ды"]', '[]', 100, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_12', 'Сөйлем құрылымы', 'Сұраулы сөйлемдер', 'Вопросительные предложения', 'A1', 'Сұрау есімдіктері: кім, не, қайда, қашан, неше, қалай, неге. Немесе сұраулық демеулік шылаулар арқылы: ма/ме, ба/бе, па/пе (сөздің соңғы дыбысына сай таңдалады).', 'Вопросительные местоимения: кім, не, қайда, қашан, неше, қалай, неге. Или вопросительные частицы (демеулік шылау): ма/ме, ба/бе, па/пе (выбираются по последнему звуку слова).', '["Сен қайда барасың?", "Бұл кітап па?", "Ол кім?", "Ол келді ме?"]', '[]', 120, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_14', 'Сан есім', 'Сан есімдер және есептеу', 'Числительные и счёт', 'A1', 'Қазақ тілінде сан есімнен кейін зат есімге көптік жалғау жалғанбайды.', 'В казахском языке после числительного существительное не получает окончание множественного числа.', '["бес бала (дұрыс емес: бес балалар)", "он кітап (дұрыс емес: он кітаптар)", "үш күн"]', '[]', 140, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_15', 'Есімдік', 'Жіктеу есімдіктері', 'Личные местоимения', 'A1', 'Мен, сен, сіз, ол, біз, сендер, сіздер, олар. Сіз — құрмет формасы.', 'Мен (я), сен (ты), Сіз (Вы — вежл.), ол (он/она), біз (мы), сендер (вы — мн.), Сіздер (Вы — мн. вежл.), олар (они). Сіз — вежливая форма.', '["Мен студентпін", "Сіз мұғалімсіз", "Олар оқиды"]', '[]', 150, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_01', 'Дыбыс үндестігі', 'Буын үндестігі (сингармонизм)', 'Гармония гласных (сингармонизм)', 'A1', 'Қазақ тілінде жуан дауысты дыбыстар мен жіңішке дауысты дыбыстар бір сөзде араласып қолданылмайды.', 'В казахском языке твёрдые и мягкие гласные не смешиваются в одном слове.', '["бала-лар (жуан)", "тіл-дер (жіңішке)", "кітап-тар (жуан)"]', '["Кейбір кірме сөздерде буын үндестігі сақталмайды"]', 10, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_02', 'Дыбыс үндестігі', 'Үндестік заңы - дауыссыз дыбыстар үндесуі', 'Ассимиляция согласных', 'A1', 'Қосымшаның басқы дыбысы сөздің соңғы дыбысына үндесіп өзгереді: қатаң дыбыстан кейін қатаң (-тан/-тен), ұяң не үнді дыбыстан кейін ұяң (-дан/-ден), дауыстыдан кейін де ұяң (-дан/-ден) қосымша жалғанады.', 'Начальный звук аффикса ассимилируется с конечным звуком основы. После глухого согласного — глухой вариант (-тан/-тен), после звонкого или сонорного — звонкий (-дан/-ден) ON CONFLICT (id) DO NOTHING; после гласного — также звонкий (-дан/-ден).', '["тас-тан (қатаң+қатаң)", "қала-дан (дауысты+ұяң)", "мал-дан (үнді+ұяң)", "қыз-дан (ұяң+ұяң)"]', '[]', 20, '2026-04-21 21:35:28.437388+00');
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_05', 'Зат есім', 'Тәуелдік жалғаулары', 'Притяжательные окончания', 'A2', 'Тәуелдік жалғаулары заттың кімдікі екенін білдіреді: -м/-ым/-ім (менің), -ң/-ың/-ің (сенің), -ңыз/-ңіз (Сіздің), -сы/-сі (оның), -мыз/-міз/-ымыз/-іміз (біздің), -ларың/-леріңіз (сендердің/Сіздердің), -лары/-лері (олардың).', 'Притяжательные окончания показывают, чьим является предмет (вопрос «кімдікі?»). Имеют твёрдые и мягкие варианты по гармонии гласных.', '["үй-ім (мой дом)", "үй-ің (твой дом)", "үй-і (его дом)", "үй-іміз (наш дом)", "кітаб-ым (п→б перед гласной)"]', '["Дауыссызға аяқталған негізде дауыстыдан басталатын тәуелдік жалғауы алдында п→б, к→г, қ→ғ алмасуы мүмкін: кітап → кітабым, тарақ → тарағым."]', 50, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_07', 'Етістік', 'Етістіктің шақтары: Осы шақ', 'Времена глагола: Настоящее время', 'A2', 'Нақ осы шақ көсемше қосымшасы (-п дауыстыдан кейін; -ып/-іп дауыссыздан кейін, буын үндестігіне сай) + жатыр/отыр/тұр/жүр көмекші етістіктерімен жасалады.', 'Настоящее (актуальное) время образуется деепричастной формой (-п после гласного; -ып/-іп после согласного, по гармонии гласных) + вспомогательные глаголы жатыр/отыр/тұр/жүр.', '["Мен оқып жатырмын", "Сен жазып отырсың", "Олар сабақ оқып жүр", "Ол кел-іп жатыр"]', '[]', 70, '2026-04-21 21:35:28.437388+00');
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_11', 'Сөйлем құрылымы', 'Сөйлемдегі сөздердің орын тәртібі', 'Порядок слов в предложении', 'A1', 'Қазақ тілі — SOV-тіл. Негізгі тәртіп: Бастауыш + Толықтауыш + Баяндауыш. Пысықтауыш әдетте бастауыш пен баяндауыштың арасында тұрады, орны икемді.', 'Казахский — язык SOV. Базовый порядок: Подлежащее + Дополнение + Сказуемое. Обстоятельства располагаются гибко, чаще между подлежащим и сказуемым.', '["Мен кітап оқыдым (Я читал книгу)", "Бала мектепке барды (Ребёнок пошёл в школу)"]', '["Сұраулы сөйлемдерде сөз тәртібі өзгеруі мүмкін"]', 110, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_18', 'Фонетика', 'Қазақ тіліне тән дыбыстар', 'Специфические звуки казахского языка', 'A1', 'Қазақ тілінде 9 тән дыбыс бар: ә, і, ө, ү, ұ, қ, ғ, ң, һ.', 'В казахском языке 9 специфических звуков: ә, і, ө, ү, ұ, қ, ғ, ң, һ.', '["Ә — әке (отец)", "Қ — қала (город)", "Ғ — тағам (еда)", "Ң — таң (рассвет)", "Ұ — ұл (сын)", "Ө — өзен (река)"]', '[]', 180, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_19', 'Емле', 'Бас әріп ережелері', 'Правила заглавной буквы', 'A2', 'Бас әріппен жазылады: сөйлем басы, жалқы есімдер, географиялық атаулар, мемлекет атаулары, мекемелер мен ұйымдардың аттары.', 'С заглавной буквы: начало предложения, имена собственные, географические названия, названия государств, наименования учреждений и организаций.', '["Астана", "Абай Құнанбайұлы", "Қазақстан Республикасы", "Әл-Фараби атындағы ҚазҰУ"]', '[]', 190, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_21', 'Мақал-мәтелдер', 'Қазақ мақал-мәтелдері', 'Казахские пословицы и поговорки', 'B1', 'Мақал-мәтелдер — халық даналығының айнасы. Тіл үйренуде маңызды.', 'Пословицы и поговорки — зеркало народной мудрости. Важны при изучении языка.', '["Тіл — қылыштан өткір", "Білімді мың жасайды", "Еңбек етсең ерінбей, тояды қарның тіленбей", "Жақсы сөз — жарым ырыс"]', '[]', 210, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_13', 'Шылаулар', 'Септеулік шылаулар', 'Послелоги', 'B1', 'Септеулік шылаулар зат есімнен кейін тұрып, мекенді, уақытты, себепті білдіреді: үшін, туралы, арқылы, бойынша, сияқты, т.б. Әр шылау өзінен бұрынғы сөздің белгілі септік формасын талап етеді (есімдіктерден кейін «үшін», «туралы» — ілік септігін, ал зат есімдерден кейін атау септігін талап етеді).', 'Послелоги стоят после существительного и выражают место, время, причину: үшін, туралы, арқылы, бойынша, сияқты и т.д. Каждый послелог требует определённой падежной формы предшествующего слова (после местоимений «үшін», «туралы» — родительный падеж, после существительных — именительный).', '["сен үшін (для тебя)", "тіл туралы (о языке)", "көпір арқылы (через мост)", "менің ойымша (по моему мнению)"]', '[]', 130, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_16', 'Жұрнақтар', 'Сөз тудырушы жұрнақтар', 'Словообразовательные суффиксы', 'B1', 'Зат есімнен сын есім: -лы/-лі, -ды/-ді, -сыз/-сіз. Етістіктен зат есім: -ыс/-іс, -у (тұйық етістік / іс-әрекеттің атауы).', 'От существительного к прилагательному: -лы/-лі, -ды/-ді, -сыз/-сіз. От глагола к существительному: -ыс/-іс, -у (имя действия / отглагольное существительное).', '["күш-ті (сильный)", "су-сыз (безводный)", "оқу (учёба/чтение)", "жаз-у (письмо)"]', '[]', 160, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_17', 'Етістік', 'Етістіктің рай категориясы', 'Наклонения глагола', 'B2', 'Ашық рай (баяндау, шақ жұрнақтары арқылы) ON CONFLICT (id) DO NOTHING; бұйрық рай — нөлдік форма (бар!, кел!), жұмсартқан -шы/-ші (баршы, келші), құрметті -ңыз/-ңіз (барыңыз, келіңіз); қалау рай (-ғы/-гі келеді: барғым келеді); шартты рай (-са/-се: келсе).', 'Изъявительное (баяндау, через временные суффиксы); повелительное — нулевая форма для 2-го л. ед.ч. (бар!, кел!), смягчённое -шы/-ші (баршы — «иди-ка»), вежливое -ңыз/-ңіз (барыңыз); желательное (-ғы/-гі келеді: барғым келеді — «хочу пойти»); условное (-са/-се: келсе — «если придёт»).', '["Бар! (иди!)", "Бар-шы! (иди же!)", "Бар-ыңыз (пройдите, пожалуйста)", "Мен бар-ғым келеді (хочу пойти)", "Ол кел-се (если он придёт)"]', '[]', 170, '2026-04-21 21:35:28.437388+00');
INSERT INTO grammar_rules (id, topic, title_kk, title_ru, level, description_kk, description_ru, examples, exceptions, rule_order, created_at) VALUES ('rule_20', 'Етістік', 'Есімше формалары', 'Причастные формы', 'B2', 'Есімше — етістіктің сын есім тәрізді формасы: -ған/-ген/-қан/-кен (өткен шақ есімшесі), -атын/-етін/-йтын/-йтін (дағдылы), -ар/-ер/-р (келер шақ есімшесі), -мақ/-мек (мақсатты).', 'Причастие — глагольная форма, подобная прилагательному: -ған/-ген/-қан/-кен (прошедшее), -атын/-етін/-йтын/-йтін (привычное/настояще-будущее), -ар/-ер/-р (будущее), -мақ/-мек (намеренное).', '["келген адам (пришедший человек)", "оқитын бала (ребёнок, который учится)", "барар жер (место, куда пойдёт)"]', '[]', 200, '2026-04-21 21:35:28.437388+00') ON CONFLICT (id) DO NOTHING;


--
-- Data for Name: lessons; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001002', 'Сандар мен уақыт', 'Числа и время', '1-ден 100-ге дейінгі сандар, уақытты айту.', 'Числа от 1 до 100, как называть время.', 'vocabulary', 'A1', '{"rule_ids": []}', 2, '2026-04-21 21:35:28.434024+00', 'auezov', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001003', 'Менің отбасым', 'Моя семья', 'Отбасы мүшелерінің атаулары, тәуелдік жалғаулары.', 'Названия членов семьи, притяжательные окончания.', 'vocabulary', 'A1', '{"rule_ids": ["rule_05"]}', 3, '2026-04-21 21:35:28.434024+00', 'auezov', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001004', 'Көптік жалғау', 'Множественное число', 'Көптік жалғауларының (-лар/-лер/-дар/-дер/-тар/-тер) қолданылуы.', 'Использование окончаний множественного числа.', 'grammar', 'A1', '{"rule_ids": ["rule_03", "rule_01", "rule_02"]}', 4, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001005', 'Дүкенде сатып алу', 'Покупки в магазине', 'Дүкенде сөйлесу, баға сұрау, сауда жасасу.', 'Разговор в магазине, вопросы о цене, обсуждение покупки.', 'conversation', 'A2', '{"rule_ids": []}', 5, '2026-04-21 21:35:28.434024+00', 'auezov', 'B1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001006', 'Септік жалғаулары', 'Падежные окончания', 'Қазақ тіліндегі 7 септік және олардың жалғаулары.', '7 падежей казахского языка и их окончания.', 'grammar', 'A2', '{"rule_ids": ["rule_04", "rule_02"]}', 6, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001007', 'Етістік шақтары', 'Времена глагола', 'Осы, өткен және келер шақ жасалуы.', 'Образование настоящего, прошедшего и будущего времён.', 'grammar', 'A2', '{"rule_ids": ["rule_07", "rule_08", "rule_09", "rule_10"]}', 7, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'B2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001008', 'Мейрамханада тапсырыс', 'Заказ в ресторане', 'Тапсырыс беру, тағамдар атаулары.', 'Сделать заказ, названия блюд.', 'conversation', 'B1', '{"rule_ids": []}', 8, '2026-04-21 21:35:28.434024+00', 'auezov', 'B2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001009', 'Сын есімнің шырайлары', 'Степени сравнения прилагательных', 'Жай, салыстырмалы, күшейтпелі, асырмалы шырайлар.', 'Положительная, сравнительная, эмфатическая (күшейтпелі), превосходная (асырмалы) степени.', 'grammar', 'B1', '{"rule_ids": ["rule_06"]}', 9, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'B1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001010', 'Іскерлік қазақ тілі', 'Деловой казахский', 'Іскерлік хат, ресми стиль, сыпайы тұлғалар.', 'Деловое письмо, официальный стиль, вежливые формы.', 'business', 'B2', '{"rule_ids": []}', 10, '2026-04-21 21:35:28.434024+00', 'abai', 'C1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001011', 'Сөйлемдегі сөздердің орны', 'Порядок слов в предложении', 'Қазақ тілінде SOV құрылымы: бастауыш–толықтауыш–баяндауыш.', 'Казахский — SOV-язык: подлежащее, дополнение, сказуемое.', 'grammar', 'A2', '{"rule_ids": ["rule_11"]}', 11, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001012', 'Сұраулы сөйлемдер', 'Вопросительные предложения', 'Ма/ме/ба/бе сұраулық шылауы, сұрау сөздер, интонация.', 'Вопросительные частицы ма/ме/ба/бе, вопросительные слова.', 'grammar', 'A1', '{"rule_ids": ["rule_12"]}', 12, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001013', 'Септеулік шылаулар', 'Послелоги', 'Арқылы, үшін, туралы, бойынша, қарсы — септеулік шылаулардың қолданылуы.', 'Послелоги арқылы, үшін, туралы, бойынша, қарсы и их употребление.', 'grammar', 'B1', '{"rule_ids": ["rule_13"]}', 13, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'B1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001014', 'Сан есімдер және есептеу', 'Числительные и счёт', 'Есептік, реттік, жинақтық, болжалдық сан есімдер.', 'Количественные, порядковые, собирательные, приблизительные числительные.', 'grammar', 'A1', '{"rule_ids": ["rule_14"]}', 14, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001015', 'Жіктеу есімдіктері', 'Личные местоимения', 'Мен, сен, сіз, ол, біз, сендер, сіздер, олар — жіктелуі.', 'Я, ты, Вы (вежл.), он/она, мы, вы (мн.), Вы (мн. вежл.), они — склонение по лицам и числам.', 'grammar', 'A1', '{"rule_ids": ["rule_15"]}', 15, '2026-04-21 21:35:28.434024+00', 'auezov', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001016', 'Сөз тудырушы жұрнақтар', 'Словообразовательные суффиксы', '-шы/-ші, -лық/-лік, -хана, -стан және басқа сөз тудырушы жұрнақтар.', 'Суффиксы -шы/-ші, -лық/-лік, -хана, -стан и другие словообразовательные.', 'grammar', 'B1', '{"rule_ids": ["rule_16"]}', 16, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'B1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001017', 'Етістіктің рай категориясы', 'Наклонения глагола', 'Ашық, бұйрық, шартты, қалау райлары.', 'Изъявительное, повелительное, условное, желательное наклонения.', 'grammar', 'B2', '{"rule_ids": ["rule_17"]}', 17, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'B2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001018', 'Қазақ тіліне тән дыбыстар', 'Специфические звуки казахского', 'Ә, ғ, қ, ң, ө, ұ, ү, һ, і — 9 тән дыбысты меңгеру.', 'Ә, ғ, қ, ң, ө, ұ, ү, һ, і — девять специфических звуков.', 'phonetics', 'A1', '{"rule_ids": ["rule_18"]}', 18, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001020', 'Есімше формалары', 'Причастные формы', 'Осы, өткен, келер шақ есімшелері: оқитын (дағдылы), оқыған (өткен), оқыр (келер).', 'Причастия: оқитын (привычное / настояще-будущее), оқыған (прошедшее), оқыр (будущее).', 'grammar', 'B2', '{"rule_ids": ["rule_20"]}', 20, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'B2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001001', 'Амандасу және танысу', 'Приветствие и знакомство', 'Қазақша сәлемдесу, өзіңізді таныстыру, қарапайым сұрақ қою.', 'Казахские приветствия, как представиться, простые вопросы.', 'conversation', 'A1', '{"rule_ids": ["rule_01"]}', 1, '2026-04-21 21:35:28.434024+00', 'abai', 'A1') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001019', 'Бас әріп ережелері', 'Правила заглавной буквы', 'Сөйлем басы, жалқы есімдер, географиялық атаулар, мекемелер мен ұйымдардың аттары.', 'Начало предложения, имена собственные, географические названия, наименования учреждений.', 'orthography', 'A2', '{"rule_ids": ["rule_19"]}', 19, '2026-04-21 21:35:28.434024+00', 'baitursynuly', 'A2') ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, title_kk, title_ru, description_kk, description_ru, topic, difficulty, content, sort_order, created_at, mentor_track, required_level) VALUES ('00000000-0000-4000-8000-000000001021', 'Қазақ мақал-мәтелдері', 'Казахские пословицы и поговорки', 'Халық даналығы, жиі кездесетін мақал-мәтелдер және олардың мағынасы.', 'Народная мудрость: частые пословицы и их значение.', 'culture', 'B1', '{"rule_ids": ["rule_21"]}', 21, '2026-04-21 21:35:28.434024+00', 'abai', 'B1') ON CONFLICT (id) DO NOTHING;


--
-- Data for Name: test_questions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('0206dd9f-9192-41c0-9fb7-489a4fb209eb', 'level', 'grammar', 'A1', 'Дұрыс жауапты таңдаңыз: Мен мектепке ___.', 'Выберите правильный ответ: Я в школу ___.', '["барамын", "барасың", "барады", "барамыз"]', 'барамын', '"Мен" жіктеу есімдігімен етістіктің 1-жақ жекеше түрі қолданылады: барамын.', 'С личным местоимением "Мен" используется форма 1-го лица единственного числа: барамын.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('b3e640c6-cdaa-4dcf-8dc5-a0c9f4208f4a', 'level', 'vocabulary', 'A1', '"Мұғалім" сөзінің мағынасы:', 'Значение слова "Мұғалім":', '["Учитель", "Ученик", "Директор", "Врач"]', 'Учитель', 'Мұғалім — оқытушы, мектепте сабақ беретін адам.', 'Мұғалім — учитель, человек, который ведёт уроки в школе.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('0eb16eea-747d-4688-bc8d-dce775c44151', 'level', 'grammar', 'A1', '"Ол кітап оқы___" — болымсыз етістіктің дұрыс формасын таңдаңыз.', '"Ол кітап оқы___" — выберите правильную отрицательную форму.', '["-майды", "-мады", "-мақ", "-мас"]', '-майды', 'Осы шақтағы болымсыздық: -майды/-мейді.', 'Отрицание в настоящем времени: -майды/-мейді.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('9ca4c130-e60e-47ef-b448-b3c9db286af1', 'level', 'vocabulary', 'A1', '"Сәлеметсіз бе!" сөзінің мағынасы:', 'Значение выражения "Сәлеметсіз бе!":', '["Здравствуйте!", "До свидания!", "Спасибо!", "Извините!"]', 'Здравствуйте!', '"Сәлеметсіз бе!" — ресми амандасу формасы.', '"Сәлеметсіз бе!" — официальная форма приветствия.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('1854e81c-6c7c-4590-afcb-7bfd8b69bf25', 'level', 'grammar', 'A2', 'Ілік септігінің жалғауын дұрыс қойыңыз: бала___', 'Поставьте окончание родительного падежа: бала___', '["-ның", "-нің", "-дың", "-тың"]', '-ның', 'Дауысты дыбысқа аяқталған жуан буынды сөздерге -ның жалғанады.', 'К словам с твёрдым слогом, оканчивающимся на гласный, прибавляется -ның.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('dc0b58ca-bfc2-4402-8ab3-93110ca69439', 'level', 'grammar', 'A2', 'Жатыс септігінің дұрыс жалғауы: мектеп___', 'Правильное окончание местного падежа: мектеп___', '["-те", "-де", "-та", "-да"]', '-те', 'Қатаң дауыссыз дыбысқа аяқталған жіңішке буынды сөзге -те жалғанады.', 'К словам с мягким слогом, оканчивающимся на глухой согласный, прибавляется -те.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('73642cdc-265d-4761-a723-41b99a22d88f', 'level', 'vocabulary', 'A2', '"Ауа райы" дегеніміз не?', 'Что означает "Ауа райы"?', '["Погода", "Природа", "Воздух", "Климат"]', 'Погода', '"Ауа райы" — метеорологиялық жағдай, погода.', '"Ауа райы" — метеорологические условия, погода.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('ce689be4-f2bd-4d87-a8cc-b30b9d20880c', 'level', 'grammar', 'B1', 'Салыстырмалы шырайдың дұрыс формасы: үлкен →', 'Правильная форма сравнительной степени: үлкен →', '["үлкенірек", "ең үлкен", "аса үлкен", "үлкендеу"]', 'үлкенірек', 'Салыстырмалы шырай -рақ/-рек жұрнағымен жасалады: үлкенірек.', 'Сравнительная степень образуется суффиксом -рақ/-рек: үлкенірек.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e1f0d503-73f0-4548-bc0c-6ce18633a608', 'level', 'grammar', 'B1', 'Шартты рай формасын табыңыз:', 'Найдите форму условного наклонения:', '["барса", "барды", "барады", "барған"]', 'барса', 'Шартты рай -са/-се жұрнағымен жасалады.', 'Условное наклонение образуется суффиксом -са/-се.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('0e13606e-21cc-403f-ad96-ef626688d1c3', 'level', 'grammar', 'B1', 'Қай сөйлемде көмектес септік қолданылған?', 'В каком предложении использован творительный падеж?', '["Мен досыммен бардым", "Мен мектепке бардым", "Мен кітап оқыдым", "Мен үйде отырмын"]', 'Мен досыммен бардым', 'Көмектес септік -мен/-бен/-пен жалғауларымен жасалады. "Досыммен" — көмектес септік.', 'Творительный падеж образуется окончаниями -мен/-бен/-пен. "Досыммен" — творительный падеж.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('f513b5b9-cfae-4282-818d-ed9f81225f50', 'level', 'vocabulary', 'B1', '"Қастерлеу" сөзінің мағынасы:', 'Значение слова "Қастерлеу":', '["Ценить, беречь", "Ненавидеть", "Забывать", "Терять"]', 'Ценить, беречь', '"Қастерлеу" — қадірлеу, бағалау, сақтау.', '"Қастерлеу" — ценить, беречь, дорожить.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('3e2cc79f-23e1-458e-9ce3-6212a24a08e5', 'level', 'grammar', 'B1', 'Септеулік шылауды табыңыз:', 'Найдите послелог:', '["туралы", "және", "бірақ", "себебі"]', 'туралы', '"Туралы" — септеулік шылау, "жайлы" мағынасын береді.', '"Туралы" — послелог, означает "о, про".') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('52cae3a8-c660-483f-a161-e4cfe11d4a6d', 'kaztest', 'grammar', 'B1', 'Осы шақ: Мен кітап___.', 'Настоящее время: Мен кітап___.', '["оқимын", "оқыдым", "оқимыз", "оқитын"]', 'оқимын', 'Мен — 1-жақ, жекеше, осы шақ: -мын.', '1-е лицо ед.ч. наст.вр. — -мын.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('d4e2a470-3c97-4992-9da7-31b0ba1c469b', 'level', 'grammar', 'A2', 'Өткен шақтың дұрыс формасы: Біз кеше кино___', 'Правильная форма прошедшего времени: Мы вчера кино___', '["көрдік", "көреміз", "көрген", "көрсек"]', 'көрдік', '"Біз" — 1-жақ көпше, жедел өткен шақ: көрдік.', '"Біз" — 1-е лицо множественного числа, недавнопрошедшее (жедел өткен шақ): көрдік.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e96aa208-eb86-4a51-af0f-d178ae17c334', 'level', 'grammar', 'B2', 'Күрделі сөйлемнің қай түрі: "Күн жауса, біз үйде отырамыз"?', 'Какой тип сложного предложения: "Күн жауса, біз үйде отырамыз"?', '["Шартты бағыныңқылы", "Мезгілді бағыныңқылы", "Себепті бағыныңқылы", "Салалас"]', 'Шартты бағыныңқылы', '"-са" жалғауы шарт білдіреді. Бұл — шартты бағыныңқылы сабақтас құрмалас сөйлем.', 'Суффикс "-са" выражает условие. Это — условное придаточное сложноподчинённое предложение.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('c8611647-6c1c-4a08-bebb-779ec145387d', 'level', 'grammar', 'B2', 'Ырықсыз етістің формасы қай сөйлемде?', 'В каком предложении страдательный залог?', '["Мақала жазылды", "Мен мақала жаздым", "Ол мақала жазады", "Мақала жазу керек"]', 'Мақала жазылды', 'Ырықсыз етіс -ыл/-іл, -л жұрнағымен жасалады: жаз-ыл-ды.', 'Страдательный залог образуется суффиксом -ыл/-іл, -л: жаз-ыл-ды.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('4e625ce1-1e2a-42a4-9be5-99d93493f1d0', 'level', 'grammar', 'C1', 'Қай сөйлемде модальдік мәні бар?', 'В каком предложении есть модальное значение?', '["Баруым керек", "Мен бардым", "Ол барады", "Біз барамыз"]', 'Баруым керек', '"Керек" — модальдік сөз, қажеттілікті білдіреді.', '"Керек" — модальное слово, выражает необходимость.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('73c32572-710b-4cbd-a008-168682039aaf', 'level', 'vocabulary', 'C1', '"Зердесіне жаттау" фразеологизмінің мағынасы:', 'Значение фразеологизма "Зердесіне жаттау":', '["Запомнить навсегда", "Забыть", "Записать", "Рассказать"]', 'Запомнить навсегда', '"Зердесіне жаттау" — есіне мықтап жаттау, ұмытпау.', '"Зердесіне жаттау" — твёрдо запомнить, не забыть.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('f146d067-5e17-40aa-824a-6d1c4af60065', 'kaztest', 'reading', 'B1', 'Мәтінді оқып, сұраққа жауап беріңіз: "Қазақстан — Орталық Азиядағы ең үлкен мемлекет. Астанасы — Астана қаласы." Қазақстанның астанасы қай қала?', 'Прочитайте текст и ответьте: "Қазақстан — крупнейшее государство в Центральной Азии. Столица — город Астана." Какой город является столицей Казахстана?', '["Астана", "Алматы", "Шымкент", "Қарағанды"]', 'Астана', 'Мәтінде "Астанасы — Астана қаласы" деп жазылған.', 'В тексте указано: "Столица — город Астана".') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('384374ef-503c-4a6c-b21d-9a39e2405a77', 'kaztest', 'grammar', 'B1', 'Бос орынды толтырыңыз: Ол кеше Алматы___ келді.', 'Заполните пропуск: Он вчера из Алматы___ приехал.', '["-дан", "-ға", "-да", "-мен"]', '-дан', 'Шығыс септік — қайдан? сұрағына жауап береді: Алматыдан.', 'Исходный падеж отвечает на вопрос откуда?: Алматыдан.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('b36fb77f-f8cd-4549-9870-9a6df63c4a42', 'thematic', 'family', 'A1', '"Әке" сөзінің мағынасы:', 'Значение слова "Әке":', '["Отец", "Мать", "Брат", "Дедушка"]', 'Отец', 'Әке — ата, папа. Ана — мама.', 'Әке — отец, папа. Ана — мама.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('1612a731-7cb7-4a87-b612-aa78be4d70ca', 'thematic', 'family', 'A1', '"Аға" дегеніміз кім?', 'Кто такой "Аға"?', '["Старший брат", "Младший брат", "Отец", "Дедушка"]', 'Старший брат', 'Аға — үлкен ұл бала. Іні — кіші ұл бала.', 'Аға — старший брат. Іні — младший брат.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('455bfec4-77d8-4c33-b1bd-5237026f2181', 'thematic', 'food', 'A1', '"Нан" дегеніміз не?', 'Что такое "Нан"?', '["Хлеб", "Мясо", "Молоко", "Вода"]', 'Хлеб', 'Нан — тамақтың негізгі түрі, хлеб.', 'Нан — основной продукт питания, хлеб.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('119c1de3-81bc-4fba-872b-daa72b8045ff', 'thematic', 'colors', 'A1', '"Көк" түстің мағынасы:', 'Значение цвета "Көк":', '["Синий/голубой", "Красный", "Жёлтый", "Зелёный"]', 'Синий/голубой', 'Көк — аспан түсі. Сонымен қатар «жасыл» мағынасын да береді.', 'Көк — цвет неба. Также может означать «зелёный».') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('d5840d8e-eb9a-461d-9415-655dc7eaa365', 'thematic', 'numbers', 'A1', '"Он бес" дегеніміз қанша?', 'Сколько означает "Он бес"?', '["15", "50", "5", "10"]', '15', 'Он = 10, бес = 5. Он бес = 15.', 'Он = 10, бес = 5. Он бес = 15.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('8b1e4b3e-8c77-46d6-b4d9-110e7e540eb8', 'thematic', 'days', 'A1', '"Дүйсенбі" — аптаның қай күні?', '"Дүйсенбі" — какой день недели?', '["Понедельник", "Вторник", "Среда", "Четверг"]', 'Понедельник', 'Дүйсенбі — аптаның бірінші жұмыс күні.', 'Дүйсенбі — первый рабочий день недели.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('268ee051-2b41-44c3-be8a-a95fc7bf73f8', 'level', 'grammar', 'A1', '"Бұл кітап" — қай сөз сілтеу есімдігі?', '"Бұл кітап" — какое слово является указательным местоимением?', '["Бұл", "Кітап", "Екеуі де", "Ешқайсысы"]', 'Бұл', '"Бұл" — сілтеу есімдігі (бұл, сол, ол, мынау, анау).', '"Бұл" — указательное местоимение (бұл, сол, ол, мынау, анау).') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('f1edba32-d6ba-49a6-9440-4648eac47641', 'level', 'grammar', 'A2', '"Мен кітап оқуды жақсы көремін" — қай сөз етістік?', '"Мен кітап оқуды жақсы көремін" — какое слово является глаголом?', '["көремін", "кітап", "жақсы", "оқуды"]', 'көремін', '"Көремін" — "көру" етістігінің 1-жақ жекеше формасы.', '"Көремін" — форма 1-го лица единственного числа глагола "көру".') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e82b393f-c74b-464e-9991-67ce472bd5a9', 'level', 'vocabulary', 'A2', '"Кітапхана" дегеніміз не?', 'Что такое "Кітапхана"?', '["Библиотека", "Книжный магазин", "Школа", "Музей"]', 'Библиотека', 'Кітапхана — кітаптар сақталатын және оқылатын мекеме.', 'Кітапхана — учреждение, где хранятся и читаются книги.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('87c26c54-fb4d-4797-b21c-e83170478255', 'level', 'grammar', 'B1', 'Күрделі етістікті табыңыз:', 'Найдите составной глагол:', '["оқып шықты", "оқыды", "оқиды", "оқыр"]', 'оқып шықты', 'Күрделі етістік негізгі етістік + көмекші етістіктен құралады: оқып шықты.', 'Составной глагол = основной глагол + вспомогательный: оқып шықты.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('886f2c88-f90b-4a66-b2f4-5e4795887687', 'level', 'grammar', 'C1', 'Төмендегі сөйлемдегі стилистикалық қатені табыңыз: "Мен бүгін базарға барып, нан мен сүт сатып алдым."', 'Найдите стилистическую ошибку: "Мен бүгін базарға барып, нан мен сүт сатып алдым."', '["Қатесі жоқ", "\"базарға\" орнына \"дүкенге\"", "\"сатып алдым\" орнына \"алдым\"", "\"барып\" орнына \"барды\""]', 'Қатесі жоқ', 'Сөйлемде стилистикалық қате жоқ.', 'В предложении нет стилистической ошибки.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('89c989d0-c29f-4fff-821d-814b9344f6c5', 'level', 'grammar', 'C2', '"Тасқа тамған су тас жарады" — бұл қандай стилистикалық тәсіл?', '"Тасқа тамған су тас жарады" — какой стилистический приём?', '["Мақал (пословица)", "Теңеу (сравнение)", "Метафора", "Эпитет"]', 'Мақал (пословица)', 'Бұл — қазақ мақалы, "Капля камень точит" мағынасында.', 'Это казахская пословица, означает "Капля камень точит".') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('270819bb-ee08-4568-aea4-93b36293e7ae', 'thematic', 'professions', 'A1', '"Дәрігер" дегеніміз кім?', 'Кто такой "Дәрігер"?', '["Врач", "Учитель", "Инженер", "Водитель"]', 'Врач', 'Дәрігер — ауруларды емдейтін маман.', 'Дәрігер — специалист, который лечит болезни.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('fd5e945c-29a7-4b26-a62c-02b1ced3385b', 'thematic', 'city', 'A2', '"Көше" сөзінің мағынасы:', 'Значение слова "Көше":', '["Улица", "Дом", "Парк", "Площадь"]', 'Улица', 'Көше — қала ішіндегі жол, улица.', 'Көше — дорога внутри города, улица.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('06aff5ec-1561-42af-b4b2-95d6a6aa97f9', 'thematic', 'nature', 'A2', '"Тау" дегеніміз не?', 'Что такое "Тау"?', '["Гора", "Река", "Озеро", "Лес"]', 'Гора', 'Тау — жер бетінің биік бөлігі.', 'Тау — возвышенная часть земной поверхности, гора.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('1205cba1-ea2a-4d9d-8da5-f5c6bebe6614', 'thematic', 'weather', 'A2', '"Жаңбыр жауып тұр" — мұның мағынасы:', '"Жаңбыр жауып тұр" — это значит:', '["Идёт дождь", "Идёт снег", "Светит солнце", "Дует ветер"]', 'Идёт дождь', 'Жаңбыр — дождь, жауып тұр — идёт (сейчас).', 'Жаңбыр — дождь, жауып тұр — идёт (сейчас).') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('65213dc0-5309-4f52-97cb-ffe56f2f7ff9', 'thematic', 'greetings', 'A1', '"Сау болыңыз!" дегеніміз не?', 'Что означает "Сау болыңыз!"?', '["До свидания!", "Здравствуйте!", "Спасибо!", "Пожалуйста!"]', 'До свидания!', '"Сау болыңыз" — ресми қоштасу формасы.', '"Сау болыңыз" — официальная форма прощания.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('5f07fdc9-9623-44d2-896d-bf7c6548b209', 'thematic', 'greetings', 'A1', '"Рахмет" дегеніміз не?', 'Что означает "Рахмет"?', '["Спасибо", "Пожалуйста", "Извините", "Привет"]', 'Спасибо', '"Рахмет" — алғыс білдіру сөзі.', '"Рахмет" — слово благодарности.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e17eebcf-dd1b-4c54-bb58-4b7ff6872c5b', 'level', 'grammar', 'A1', 'Жіктік жалғауды дұрыс қойыңыз: Мен студент___.', 'Поставьте правильное личное окончание: Мен студент___.', '["-пін", "-сің", "-міз", "—"]', '-пін', '"Мен" — 1-жақ жекеше. Қатаң дыбыстан кейін: -пін/-пын.', '"Мен" — 1-е лицо ед. ч. После глухого согласного: -пін/-пын.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('9df83b2b-01c6-433b-83cf-02b1aa1dd350', 'level', 'grammar', 'A2', 'Қай сөйлем дұрыс?', 'Какое предложение правильное?', '["Бес бала ойнап жатыр", "Бес балалар ойнап жатыр", "Бес балалардың ойнап", "Бесеу бала ойнап"]', 'Бес бала ойнап жатыр', 'Сан есімнен кейін зат есімге көптік жалғау жалғанбайды.', 'После числительного существительное не получает окончание множественного числа.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('f7e39af0-2a55-4c7e-8ff0-9398a3351a98', 'kaztest', 'writing', 'C1', 'Қай сөйлем ресми іс-қағаздар стиліне сай?', 'Какое предложение соответствует официально-деловому стилю?', '["Хабарламаны қабылдауыңызды сұраймын", "Хабарламаны алшы", "Хабарламаны аларсың ба", "Хабарламаны ал"]', 'Хабарламаны қабылдауыңызды сұраймын', 'Ресми стильде сыпайы, ресми тұлғалар қолданылады.', 'В официальном стиле используются вежливые, официальные формы.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('0ad2eb6c-adc8-44a7-b4e6-b1770472d9e9', 'kaztest', 'grammar', 'A2', 'Барыс септігі: мектеп___ барамын', 'Дательный падеж: мектеп___ барамын', '["-ке", "-қа", "-ға", "-а"]', '-ке', 'Жіңішке + қатаң = -ке.', 'Мягкая + глухой = -ке.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('037ca44f-80ea-491a-ba9c-5eeef18f4971', 'kaztest', 'grammar', 'B2', 'Табыс септігінің жалғауын табыңыз: Мен хат___ жаздым.', 'Найдите окончание винительного падежа: Мен хат___ жаздым.', '["-ты", "-ні", "-та", "-тан"]', '-ты', 'Табыс септік — нені? кімді? сұрағына жауап. Хат → хатты.', 'Винительный падеж — отвечает на вопрос что? кого? Хат → хатты.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('9d4d3fb0-cacd-45cb-b5b0-2099ba3ec7e2', 'level', 'vocabulary', 'A1', '"Су" дегеніміз не?', 'Что такое "Су"?', '["Вода", "Молоко", "Чай", "Сок"]', 'Вода', 'Су — H₂O, адам өмірі үшін қажетті сұйықтық.', 'Су — H₂O, жидкость, необходимая для жизни человека.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('ce4b5c2d-6301-47d3-93f4-9a8adf358275', 'level', 'grammar', 'B2', '"Көрсеткіш" сөзіндегі сөз тудырушы жұрнақ:', 'Словообразовательный суффикс в слове "Көрсеткіш":', '["-кіш", "-ткіш", "-іш", "-еткіш"]', '-кіш', '"Көрсет" + "-кіш" — құрал мәнді зат есім жұрнағы.', '"Көрсет" + "-кіш" — суффикс существительного со значением инструмента.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('119ae37a-87ce-45df-b952-08f558a74e09', 'level', 'grammar', 'C1', 'Кіріккен сөзді табыңыз:', 'Найдите слитное слово:', '["бүгін", "үлкен бала", "қызыл алма", "жақсы адам"]', 'бүгін', '"Бүгін" — "бұл" + "күн" сөздерінен кіріккен. Қалғандары — сөз тіркестері.', '"Бүгін" — слитное слово от "бұл" + "күн". Остальные — словосочетания.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('ad8819d8-6d40-432a-955b-640dc6fc832a', 'level', 'grammar', 'C2', 'Абай тілінің ерекшелігі қай нұсқада дұрыс көрсетілген?', 'В каком варианте правильно показана особенность языка Абая?', '["Әдеби тілдің негізін қалаушы", "Тек ауызекі тіл қолданушы", "Тек араб сөздерін пайдаланушы", "Тек орыс тілінде жазушы"]', 'Әдеби тілдің негізін қалаушы', 'Абай Құнанбайұлы — қазақ әдеби тілінің негізін қалаушы.', 'Абай Кунанбайулы — основоположник казахского литературного языка.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('2d0998b7-df3d-4302-81ec-9d76787237b8', 'kaztest', 'listening', 'A2', 'Диалог: "— Қайда барасың? — Дүкенге." Бұл адам қайда бара жатыр?', 'Диалог: "— Қайда барасың? — Дүкенге." Куда идёт этот человек?', '["В магазин", "В школу", "Домой", "На работу"]', 'В магазин', '"Дүкен" — магазин.', '"Дүкен" переводится как "магазин".') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('047ea2d8-3ad5-4a38-86eb-3196c5552ddb', 'kaztest', 'listening', 'B1', '"Ертең жаңбыр жауады" — бұл сөйлем не туралы?', '"Ертең жаңбыр жауады" — о чём это предложение?', '["Ауа райы", "Тамақ", "Көлік", "Жұмыс"]', 'Ауа райы', 'Жаңбыр — ауа райы туралы сөз.', 'Дождь — погодное явление.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('7ba7c759-9c58-4cd9-9a12-e2db3a0a7d9d', 'kaztest', 'listening', 'B2', '"Жиналыс сағат тоғызда басталады" дегеннен не түсінесіз?', 'Что вы понимаете из "Жиналыс сағат тоғызда басталады"?', '["Собрание начинается в 9", "Собрание в 10", "Собрание закончилось", "Собрания не будет"]', 'Собрание начинается в 9', 'Тоғыз — девять, басталады — начинается.', 'Тоғыз — девять, басталады — начинается.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e715a411-46a5-430a-a0a7-768d74357ed4', 'kaztest', 'reading', 'A1', '"Менің атым — Ерлан" — бұл сөйлем не туралы?', '"Менің атым — Ерлан" — о чём это предложение?', '["Аты-жөні", "Жасы", "Қалауы", "Мамандығы"]', 'Аты-жөні', '"Атым" — имя.', '"Атым" — моё имя.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('12ebcfc3-c1fc-482c-a4e5-c71bf5a9dca5', 'kaztest', 'reading', 'A2', '"Астана — Қазақстанның астанасы. Халқы 1 миллион адамнан асады." Халық саны қанша?', '"Астана — столица Казахстана. Население превышает 1 миллион." Сколько жителей?', '["1 миллионнан көп", "500 мың", "2 миллион", "10 миллион"]', '1 миллионнан көп', 'Мәтінде "1 миллион адамнан асады" делінген.', 'В тексте сказано "превышает 1 миллион".') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('61d96905-ea5e-4ac3-ad58-068e4962f3a1', 'kaztest', 'reading', 'B2', '"Абай 45 қара сөзінде адам баласын жақсы тәрбиелеу жолдарын айтады". Мәтіннің негізгі тақырыбы:', '"Абай в 45 словах-назиданиях говорит о воспитании". Главная тема:', '["Тәрбие", "Саясат", "Табиғат", "Техника"]', 'Тәрбие', '"Тәрбие" — воспитание.', 'Воспитание — главная тема.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('023968d8-70f2-47c4-8b55-da0a9ee25b72', 'kaztest', 'reading', 'C1', '"Қоғамның экономикалық дамуы білім беру жүйесіне тәуелді". Автор нені айтады?', '"Экономическое развитие общества зависит от системы образования". О чём автор?', '["Білім мен экономиканың байланысы", "Мәдениет пен спорт", "Технология мен медицина", "Саясат пен соғыс"]', 'Білім мен экономиканың байланысы', 'Мәтінде білім беру мен экономика байланысы айтылған.', 'В тексте — связь образования и экономики.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('bd0d64b5-729d-4f32-8349-066f5011a089', 'kaztest', 'grammar', 'A1', 'Дұрысын таңдаңыз: үй___', 'Выберите правильный вариант: үй___', '["-лер", "-лар", "-тар", "-дер"]', '-лер', 'Жіңішке дауыстыдан кейін -лер.', 'После мягкой гласной — -лер.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('fc8638c2-ff0d-4c0f-807d-6f1fbcd163cd', 'kaztest', 'grammar', 'A2', 'Ілік септігі: кітап___ мұқабасы', 'Родительный падеж: кітап___ мұқабасы', '["-тың", "-дың", "-ның", "-нің"]', '-тың', 'Қатаң дыбыстан кейін -тың.', 'После глухого согласного — -тың.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('9b8368f2-7c3d-472c-b3c0-90c9ad49eebb', 'kaztest', 'listening', 'A1', '"Сәлеметсіз бе!" — нені білдіреді?', '"Сәлеметсіз бе!" — какое это слово?', '["Сәлемдесу", "Қоштасу", "Алғыс айту", "Кешірім сұрау"]', 'Сәлемдесу', 'Сыпайы сәлемдесудің формасы.', 'Вежливая форма приветствия.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('91e93a73-a3a4-4a98-bd6c-018821ef20ff', 'kaztest', 'grammar', 'A1', 'Көптік жалғауын табыңыз: бала___', 'Найдите окончание множественного числа: бала___', '["-лар", "-тар", "-дер", "-лер"]', '-лар', 'Жуан дауыстыдан кейін -лар жалғанады.', 'После твёрдого гласного звука — -лар.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('fc831028-ef97-450d-a7f5-932dc870a4ae', 'kaztest', 'grammar', 'B1', 'Өткен шақ: Ол кеше үйде ___.', 'Прошедшее время: Ол кеше үйде ___.', '["болды", "болады", "болмақ", "болған еді"]', 'болды', 'Жедел өткен шақ — -ды.', 'Недавнопрошедшее время — -ды.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('ee35d8c6-687b-4074-977d-80a106aa6780', 'kaztest', 'grammar', 'B2', 'Есімше: кітап оқи___ бала', 'Причастие: кітап оқи___ бала', '["-тын", "-ған", "-ар", "-мақ"]', '-тын', 'Осы/келер шақ есімшесі — -тын.', 'Причастие настоящего/будущего — -тын.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('d589d10f-172d-4123-83c7-947dbea8221f', 'kaztest', 'grammar', 'C1', 'Шартты рай: Егер уақыт бол___, келер едім.', 'Условное наклонение: Егер уақыт бол___, келер едім.', '["-са", "-се", "-ды", "-ған"]', '-са', 'Жуан түбірге -са жалғанады.', 'К твёрдой основе — -са.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('d57e42d5-b0fb-4f57-95e5-91d7e17c5678', 'kaztest', 'vocabulary', 'A1', '"Су" сөзінің қарама-қарсы мағынасы:', 'Антоним слова "су":', '["от", "жер", "ауа", "тас"]', 'от', 'Су ↔ от (вода ↔ огонь).', 'Вода ↔ огонь.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('1a33f518-f074-4f0e-affe-34a1a82136e1', 'kaztest', 'vocabulary', 'A2', '"Үлкен" синонимі:', 'Синоним слова "үлкен":', '["зор", "кіші", "жас", "биік"]', 'зор', 'Үлкен = зор (большой).', 'Үлкен = зор (большой).') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('c6da0c1b-5465-4924-bdd2-99f768dcc7ad', 'kaztest', 'vocabulary', 'B1', '"Қоғам" сөзіне жақын:', 'Близко по значению к "қоғам":', '["әлеумет", "ғылым", "ауыл", "еңбек"]', 'әлеумет', 'Қоғам — общество, әлеумет те сондай.', 'Қоғам — общество, әлеумет — также.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('54431a4c-6cef-4b32-ae8a-8d90aeb9b383', 'kaztest', 'vocabulary', 'B2', '"Ықпал ету" мағынасы:', 'Значение "ықпал ету":', '["әсер ету", "жауап беру", "сұрау", "көмектесу"]', 'әсер ету', 'Ықпал = әсер (влияние).', 'Ықпал = әсер (влияние).') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('f236b800-a713-4d52-9711-8a0d07c7ce6c', 'kaztest', 'vocabulary', 'C1', '"Мұрагерлік" сөзінің мағынасы:', 'Значение "мұрагерлік":', '["мұра қалдыру/алу", "сатып алу", "жалға беру", "табу"]', 'мұра қалдыру/алу', 'Мұра — наследство.', 'Мұра — наследство.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('8ae36413-f200-4e12-9c02-eaa8163457d0', 'kaztest', 'writing', 'A2', 'Қайсысы дұрыс жазылған?', 'Какой вариант написан правильно?', '["Мен мектепке барамын", "Мен мектепка барамын", "Мен мектепге барамын", "Мен мектепте барамын"]', 'Мен мектепке барамын', 'Барыс септік -ке, үндестік заңы.', 'Дательный -ке, сингармонизм.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('249b942c-d58f-4257-82a6-c63499eb710d', 'kaztest', 'writing', 'B1', 'Дұрыс жазылған сөзді табыңыз:', 'Найдите правильно написанное слово:', '["қызығушылық", "қызіғышылық", "қызығыушылық", "қызышылық"]', 'қызығушылық', 'Үндестік және дұрыс жұрнақ.', 'Сингармонизм и правильный аффикс.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('590e2f18-f3cb-45b2-aaf2-96b579118c5c', 'kaztest', 'writing', 'B2', 'Қай сөйлем стилистикалық тұрғыдан дұрыс?', 'Какое предложение стилистически верно?', '["Ол өте қызықты кітап оқыды", "Ол өте қызықты кітапты оқыды", "Ол кітапты оқыды өте қызықты", "Оқыды қызықты кітапты"]', 'Ол өте қызықты кітапты оқыды', 'Табыс септік керек: кітап → кітапты.', 'Нужен винительный: кітап → кітапты.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('a2d9750e-1bf5-4404-b391-67c64ec76388', 'kaztest', 'writing', 'C1', 'Іскерлік хатта қандай тіркес сәйкес?', 'Какое выражение подходит для делового письма?', '["Құрметпен", "Жарайды", "Жарайды ма", "Келсе"]', 'Құрметпен', '"Құрметпен" — хаттың ресми аяқталуы.', '"Құрметпен" (С уважением) — официальная концовка.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('20dc8581-6fbc-492a-bebc-474ffd47dbde', 'kaztest', 'grammar', 'A1', 'Тәуелдік жалғау: менің кітаб___', 'Притяжательное окончание: менің кітаб___', '["-ым", "-ің", "-ы", "-ыңыз"]', '-ым', '1-жақ жекеше: -ым/-ім.', '1 лицо ед.ч.: -ым/-ім.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('fb05de2e-2ec4-4e27-80bc-b2daa44e99c7', 'kaztest', 'grammar', 'A2', 'Жатыс септік: Мен қалада ___.', 'Местный падеж: Мен қалада ___.', '["тұрамын", "тұрамыз", "тұрасың", "тұрады"]', 'тұрамын', '1-жақ жекеше осы шақ.', '1 лицо ед.ч. наст.вр.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('416e87f7-5538-4a5f-96b1-82303751f129', 'kaztest', 'vocabulary', 'A1', '"Ата-ана" дегеніміз не?', 'Что означает "ата-ана"?', '["Родители", "Дети", "Братья", "Соседи"]', 'Родители', 'Ата-ана — родители.', 'Ата-ана — родители.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('6e019a63-41cc-46b7-bd34-db6ad286b396', 'kaztest', 'reading', 'A2', '"Дәрігер ауруды емдейді". Дәрігер кім?', '"Дәрігер ауруды емдейді". Кто такой дәрігер?', '["Врач", "Учитель", "Инженер", "Продавец"]', 'Врач', 'Дәрігер — врач.', 'Дәрігер — врач.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('2de76204-5e81-4c80-97b2-b6dba98c0b73', 'kaztest', 'listening', 'A2', '"Бүгін сабақ жоқ" — қайсы дұрыс?', '"Бүгін сабақ жоқ" — что означает?', '["Сегодня нет урока", "Сегодня есть урок", "Завтра нет урока", "Вчера был урок"]', 'Сегодня нет урока', 'Бүгін — сегодня, жоқ — нет.', 'Бүгін — сегодня, жоқ — нет.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e6d3226b-fbb3-4a3d-88fe-a6618c3a0750', 'kaztest', 'grammar', 'C1', '"Көрмеген жерді көрсеңіз" — қай сөз тіркесі?', '"Көрмеген жерді көрсеңіз" — что за выражение?', '["шартты рай + есімше", "бұйрық рай", "хабарлы рай", "үстеу"]', 'шартты рай + есімше', 'Көрмеген — есімше, көрсеңіз — шартты рай.', 'Көрмеген — причастие, көрсеңіз — условная форма.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('ebf92b36-44b1-49c0-80f3-9e4bdf1ce61b', 'kaztest', 'vocabulary', 'B1', '"Ауызбіршілік" деген не?', 'Что означает "ауызбіршілік"?', '["бірлік", "жанжал", "бөлек", "қарсылық"]', 'бірлік', 'Ауызбіршілік — единство, согласие.', 'Ауызбіршілік — единство, согласие.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('6a088b55-ee8e-4c4c-a348-d6aa100f6907', 'kaztest', 'grammar', 'B2', 'Көсемше жалғауы: сөйле___ отырды', 'Окончание деепричастия: сөйле___ отырды', '["-й", "-ыз", "-а", "-ып"]', '-й', 'Дауыстыдан кейін -й көсемшесі.', 'После гласной — деепричастие -й.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('d991f86b-adbe-4d78-8462-1710779bbda1', 'level', 'grammar', 'B1', 'Бұйрық райдың 2-жақ сыпайы түрі: бар___', 'Повелительное наклонение, 2 лицо вежливая форма: бар___', '["-ыңыз", "-ың", "-ыңдар", "-а"]', '-ыңыз', 'Сыпайы бұйрық рай 2-жақ жекеше — -ыңыз/-іңіз.', 'Вежливая форма повелительного 2 л. ед.ч. — -ыңыз/-іңіз.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('1c1d5b83-50e8-4f4c-be38-0f776a5bd78c', 'level', 'grammar', 'B1', 'Өздік есімдігін табыңыз:', 'Найдите возвратное местоимение:', '["өзім", "мен", "бұл", "кім"]', 'өзім', 'Өздік есімдіктері: өз, өзім, өзің, өзі, өзіміз.', 'Возвратные местоимения: өз, өзім, өзің, өзі, өзіміз.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('cd44b49a-a222-4034-b92b-2bfbab6450ef', 'level', 'grammar', 'B1', 'Еліктеу сөзді табыңыз:', 'Найдите подражательное слово:', '["сарт-сұрт", "кітап", "мектеп", "әдемі"]', 'сарт-сұрт', 'Еліктеу сөздер дыбысқа еліктеуден жасалады: сарт-сұрт, тарс-тұрс.', 'Подражательные слова образуются от звукоподражания: сарт-сұрт, тарс-тұрс.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('6f55406b-b4d6-4be1-b2ad-2c9d93ab25dc', 'level', 'grammar', 'B2', 'Қалау рай формасы: Мен кітап оқы___.', 'Форма желательного наклонения: Мен кітап оқы___.', '["-ғым келеді", "-дым", "-ған", "-р"]', '-ғым келеді', 'Қалау рай — -ғы/-гі/-қы/-кі + тәуелдік + келеді.', 'Желательное наклонение — -ғы/-гі/-қы/-кі + притяжательная + келеді.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('388ede41-8ede-4be5-bf0c-c804c081b936', 'level', 'grammar', 'B2', 'Өзгелік етісті табыңыз:', 'Найдите понудительный залог:', '["жаздырды", "жазды", "жазылды", "жазысты"]', 'жаздырды', 'Өзгелік етіс -дыр/-дір/-тыр/-тір жұрнағымен жасалады: жаз-дыр-ды.', 'Понудительный залог образуется -дыр/-дір/-тыр/-тір: жаз-дыр-ды.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('b5de3fd3-0af5-4c06-969b-f44a7ffa1a5a', 'level', 'vocabulary', 'B2', '"Игілік" сөзінің мағынасы:', 'Значение слова "игілік":', '["Благо, польза", "Потеря", "Ошибка", "Печаль"]', 'Благо, польза', 'Игілік — жақсылық, пайда.', 'Игілік — благо, польза.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('4aa5bd8e-718d-48b0-8a2b-3dec0390f8c0', 'level', 'grammar', 'C1', 'Жалғаулық шылауды табыңыз:', 'Найдите союз:', '["әрі", "туралы", "қарай", "дейін"]', 'әрі', '«Әрі» — жалғаулық шылау (и, да). Қалғандары — септеуліктер.', '«Әрі» — союз (и, да). Остальные — послелоги.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('56f6b541-cc1a-4728-a3ab-273809b82ffe', 'level', 'vocabulary', 'C1', '"Парасаттылық" сөзінің мағынасы:', 'Значение слова "парасаттылық":', '["Мудрость, рассудительность", "Глупость", "Трусость", "Злость"]', 'Мудрость, рассудительность', 'Парасаттылық — ақыл-ой тереңдігі, саналылық.', 'Парасаттылық — глубина ума, рассудительность.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('8494445d-6ac2-454f-ad83-cc1786383620', 'level', 'grammar', 'C1', 'Қай сөз етістіктен жасалған зат есім?', 'Какое слово — существительное, образованное от глагола?', '["оқу", "кітап", "үй", "бала"]', 'оқу', '«Оқу» — «оқы» етістігінен -у жұрнағы арқылы жасалған тұйық етістік/зат есім.', '«Оқу» — инфинитив/отглагольное существительное от «оқы» + -у.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('788637f6-97f3-4f80-8d91-c7dd4a37b1c5', 'level', 'vocabulary', 'C1', '«Мәртебе» сөзінің мағынасы:', 'Значение слова «мәртебе»:', '["Статус, достоинство", "Низость", "Бедность", "Ошибка"]', 'Статус, достоинство', 'Мәртебе — абырой, дәреже, статус.', 'Мәртебе — честь, достоинство, статус.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('f30dc332-3d98-41ef-b886-cbaec3d01e01', 'level', 'vocabulary', 'C2', '«Ақ жол тілеу» фразеологизмінің мағынасы:', 'Значение фразеологизма «ақ жол тілеу»:', '["Пожелать счастливого пути/удачи", "Потерять дорогу", "Отказать", "Проклясть"]', 'Пожелать счастливого пути/удачи', '«Ақ жол тілеу» — сапарға шыққан адамға сәттілік тілеу.', '«Ақ жол тілеу» — пожелать счастливого пути отправляющемуся.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('33f41353-aefb-4ea5-9c55-3474ff19625c', 'level', 'grammar', 'C2', '«Жел тұрмаса, шөптің басы қимылдамайды» — мұнда қандай стильдік тәсіл?', '«Жел тұрмаса, шөптің басы қимылдамайды» — какой стилистический приём?', '["Мақал (нет дыма без огня)", "Метафора", "Эпитет", "Гипербола"]', 'Мақал (нет дыма без огня)', 'Бұл қазақ мақалы, «нет дыма без огня» мағынасында.', 'Это казахская пословица — эквивалент «нет дыма без огня».') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('c07bf2e7-a604-4400-b9b2-65e5efa2cdd1', 'level', 'vocabulary', 'C2', '«Қарашаңырақ» сөзінің мағынасы:', 'Значение слова «қарашаңырақ»:', '["Родовое гнездо, дом предков", "Новый дом", "Соседний дом", "Заброшенный дом"]', 'Родовое гнездо, дом предков', 'Қарашаңырақ — ата-бабадан қалған үй, отбасы ұйытқысы.', 'Қарашаңырақ — родовой очаг, дом, унаследованный от предков.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('5812cd7c-cc82-46a0-941f-500e77d87af3', 'level', 'grammar', 'C2', '«Ат үсті қарау» тіркесінің мағынасы:', 'Значение выражения «ат үсті қарау»:', '["Рассматривать поверхностно", "Смотреть внимательно", "Осматривать лошадь", "Готовиться"]', 'Рассматривать поверхностно', '«Ат үсті» — үстірт, жеңіл-желпі деген мағынада.', '«Ат үсті» — поверхностно, мимоходом.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('900f5452-bf80-4e7d-adc9-965177989682', 'level', 'vocabulary', 'C2', '«Жүрегіне қанжар сұққандай» дегеніміз:', 'Значение «жүрегіне қанжар сұққандай»:', '["Глубоко ранить (эмоционально)", "Обрадовать", "Успокоить", "Помочь"]', 'Глубоко ранить (эмоционально)', 'Жан дүниесін қатты жаралау мағынасындағы көркем теңеу.', 'Художественное сравнение, означающее сильную душевную рану.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('d2d29337-c3f6-4931-95f0-e6883f03c125', 'level', 'grammar', 'C2', 'Қай нұсқада көркем әдебиет стилінің белгісі бар?', 'В каком варианте — признак художественного стиля?', '["Ай нұрын шашқан түн", "Жиналыс сағат 9-да басталады", "Қаулы бекітілді", "Хабарламаны қабылдаңыз"]', 'Ай нұрын шашқан түн', 'Көркемдегіш тәсіл (метафора) — көркем әдебиет стиліне тән.', 'Метафора — признак художественного стиля.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('df830570-eea0-4fcc-9bf6-1ed72e6e2bd0', 'level', 'grammar', 'A1', 'Көптік жалғауды дұрыс қойыңыз: кітап___', 'Поставьте правильное окончание множественного числа: кітап___', '["-тар", "-лар", "-дар", "-тер"]', '-тар', '"Кітап" сөзі араб тілінен енген кірме сөз; тонкая огласовкасына (і — жіңішке дауысты) қарамастан, әдеби нормада -тар жалғауымен жазылады. Бұл — лексикалық ерекшелік.', 'Слово "кітап" — арабизм-исключение. Несмотря на тонкую гласную "і", в литературной норме закреплено окончание -тар (а не -тер по правилу сингармонизма).');
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('7a6a60e8-a666-422b-b3c9-7cf921fa5cc7', 'level', 'grammar', 'A2', 'Тәуелдік жалғауды дұрыс қойыңыз: Менің кітаб___', 'Поставьте притяжательное окончание: Менің кітаб___', '["-ім", "-ің", "-і", "-іміз"]', '-ім', '"Кітап" — жіңішке негіз ("і"), сондықтан тәуелдік 1-жақ жекеше -ім. Дауыссыздан басталатын негіз дауыстыдан басталатын қосымша алдында "п→б" алмасуынан кейін: кітабім.', '"Кітап" — мягкая основа (узкая гласная "і"), поэтому 1 л. ед.ч. — -ім. Перед гласным аффиксом "п" переходит в "б": кітабім.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('e5babf07-bbc6-4ac7-8acd-453dca08ac14', 'level', 'grammar', 'B2', 'Есімшенің дұрыс формасы: Кеше ___ адам бүгін келді.', 'Правильная форма причастия: Человек, который вчера ___, сегодня пришёл.', '["кеткен", "кететін", "кетер", "кетіп"]', 'кеткен', 'Өткен шақ есімше -ған/-ген/-қан/-кен жұрнағымен жасалады.', 'Причастие прошедшего времени образуется суффиксом -ған/-ген/-қан/-кен.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('58a73ffd-6807-4e89-9577-ab75163c8e57', 'level', 'vocabulary', 'B2', '"Кеңістік" сөзінің синонимі:', 'Синоним слова "Кеңістік":', '["Аумақ, кеңдік", "Тарылық", "Тереңдік", "Биіктік"]', 'Аумақ, кеңдік', '"Кеңістік" — кең аумақ, ашық алаң, көлем; синонимдері: аумақ, кеңдік, алаң.', '"Кеңістік" — пространство, простор, объём; синонимы: аумақ (территория), кеңдік (ширина/простор).');
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('dd2d1b3e-2406-4992-a483-a09f7926bfa4', 'kaztest', 'listening', 'B2', 'Дұрыс нұсқаны таңдаңыз: Біз ___ мектепте оқыдық.', 'Выберите правильный вариант: Мы ___ учились в школе.', '["бір", "бірге", "бірлік", "бірден"]', 'бірге', '"Бірге" — вместе, көмектес мәнді үстеу.', '"Бірге" — вместе, наречие совместности.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('9eac5f7f-911a-45ea-a069-c7869803dd30', 'kaztest', 'listening', 'A1', 'Тыңдаңыз: "Сағат неше?" Сұрақтың мағынасы не?', 'Послушайте: "Сағат неше?" Что означает вопрос?', '["Который час?", "Как дела?", "Сколько лет?", "Где ты?"]', 'Который час?', '"Сағат қанша?" — уақытты сұрау.', '"Сағат қанша?" — вопрос о времени.') ON CONFLICT (id) DO NOTHING;
INSERT INTO test_questions (id, test_type, topic, difficulty, question_kk, question_ru, options, correct_answer, explanation_kk, explanation_ru) VALUES ('dd66609e-613c-4528-8324-76767a3b48f2', 'kaztest', 'reading', 'B1', '"Қазақ халқының Наурыз мейрамы — көктемнің келуін білдіреді". Наурыз қашан тойланады?', '"Наурыз — символ прихода весны". Когда отмечается Наурыз?', '["Көктемде", "Жазда", "Күзде", "Қыста"]', 'Көктемде', 'Көктем — весна, Наурыз 22 наурызда (март).', 'Весной, 22 марта.') ON CONFLICT (id) DO NOTHING;


--
-- PostgreSQL database dump complete
--
